DROP FUNCTION IF EXISTS usr_get_last_passwords;

CREATE OR REPLACE FUNCTION usr_get_last_passwords
(
	vr_user_id 			UUID,
    vr_auto_generated	BOOLEAN,
    vr_count		 	INTEGER
)
RETURNS TABLE (
	"password"		VARCHAR, 
	auto_generated	BOOLEAN
)
AS
$$
BEGIN
	RETURN QUERY
	SELECT 	h.password, 
			h.auto_generated
	FROM usr_passwords_history AS h
	WHERE h.user_id = vr_user_id AND 
		(vr_auto_generated IS NULL OR COALESCE(h.auto_generated, FALSE) = vr_autoGenerated)
	ORDER BY h.id DESC
	LIMIT COALESCE(vr_count, 1000);
END;
$$ LANGUAGE plpgsql;

